name = "baykus"
main = "src/index.ts"
compatibility_date = "2025-11-02"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "Room" }
]
[[durable_objects.bindings]]
name = "USER_SESSION"
class_name = "UserSessionDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Room"]

[observability]
enabled = true